import React,{useEffect,useMemo,useState} from "react";
import ReactDOM from "react-dom/client";
import {io,Socket} from "socket.io-client";
import "./styles.css";

type Suit="♠"|"♥"|"♦"|"♣";
type Card={id:string;suit:Suit;rank:string;value:number};
type PlayerStatus="ACTIVE"|"RECONNECTING"|"LEFT";
type Player={id:string;name:string;totalChip:number;status:PlayerStatus;disconnectedAt:number|null};
type Ledger=Record<string,Record<string,number>>;
type RoundResult={roundNumber:number;starterId:string;reason:"knock"|"initial-trip";scores:Record<string,number>;roundNet:Record<string,number>;settlements:any[]};
type Room={code:string;hostId:string;multiplier:number;status:"waiting"|"playing"|"ended";reconnectGraceMs:number;players:Player[];ledger:Ledger;history:RoundResult[]};
type TablePlayer={id:string;name:string;totalChip:number;status:PlayerStatus;activeInRound:boolean;cardCount:number};
type GameState={myPlayerId:string;roundNumber:number;phase:"playing"|"final-round"|"showdown";hand:Card[];activeInRound:boolean;tablePlayers:TablePlayer[];starterId:string;currentPlayerId:string|null;hasDrawn:boolean;knockedBy:string|null;deckCount:number;topDiscard:Card|null;result:RoundResult|null;emojiRemaining:number};
type Reaction={id:string;playerId:string;name:string;emoji:string;seed:number};

const SESSION_KEY="scat31-session-v4";
type SavedSession={roomCode:string;playerId:string;playerToken:string};
const loadSession=():SavedSession|null=>{try{const x=localStorage.getItem(SESSION_KEY);return x?JSON.parse(x):null}catch{return null}};
const saveSession=(s:SavedSession)=>localStorage.setItem(SESSION_KEY,JSON.stringify(s));
const clearSession=()=>localStorage.removeItem(SESSION_KEY);
const socket:Socket=io(import.meta.env.DEV?"http://localhost:3001":undefined,{reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:500,reconnectionDelayMax:5000,timeout:20000});

function App(){
 const [connected,setConnected]=useState(false),[restoring,setRestoring]=useState(Boolean(loadSession())),[myPlayerId,setMyPlayerId]=useState(loadSession()?.playerId||""),[name,setName]=useState(""),[roomCode,setRoomCode]=useState(""),[multiplier,setMultiplier]=useState(2),[room,setRoom]=useState<Room|null>(null),[game,setGame]=useState<GameState|null>(null),[selectedCard,setSelectedCard]=useState<string|null>(null),[error,setError]=useState(""),[reactions,setReactions]=useState<Reaction[]>([]),[emojiRemaining,setEmojiRemaining]=useState(10),[showLedger,setShowLedger]=useState(false);
 const isHost=room?.hostId===myPlayerId,myTurn=game?.currentPlayerId===myPlayerId,myPlayer=room?.players.find(p=>p.id===myPlayerId);
 const playerName=(id:string)=>room?.players.find(p=>p.id===id)?.name||"Player";
 const score=useMemo(()=>{if(!game||game.hand.length!==3)return "-";const h=game.hand;if(h.every(c=>c.rank===h[0].rank))return 30.5;const t:Record<Suit,number>={"♠":0,"♥":0,"♦":0,"♣":0};h.forEach(c=>t[c.suit]+=c.value);return Math.max(...Object.values(t));},[game]);

 const resume=()=>{const s=loadSession();if(!s){setRestoring(false);return;}socket.emit("resume-session",{code:s.roomCode,playerId:s.playerId,playerToken:s.playerToken},(r:any)=>{setRestoring(false);if(!r?.ok){clearSession();setRoom(null);setGame(null);setMyPlayerId("");setError(r?.message||"Session หมดอายุ");return;}setMyPlayerId(r.playerId);setRoom(r.room);setError("");});};
 useEffect(()=>{const c=()=>{setConnected(true);resume()},d=()=>setConnected(false),ru=(x:Room)=>setRoom(x),gu=(x:GameState)=>{setGame(x);setMyPlayerId(x.myPlayerId);setEmojiRemaining(x.emojiRemaining??10);if(!x.hasDrawn)setSelectedCard(null)},er=(x:Reaction)=>{setReactions(v=>[...v,x]);setTimeout(()=>setReactions(v=>v.filter(a=>a.id!==x.id)),2300)};socket.on("connect",c);socket.on("disconnect",d);socket.on("room-update",ru);socket.on("game-state",gu);socket.on("emoji-reaction",er);if(socket.connected)c();return()=>{socket.off("connect",c);socket.off("disconnect",d);socket.off("room-update",ru);socket.off("game-state",gu);socket.off("emoji-reaction",er)}},[]);
 const cb=(r:any)=>{if(!r?.ok)setError(r?.message||"เกิดข้อผิดพลาด");else setError("")};
 const createRoom=()=>socket.emit("create-room",{name:name.trim(),multiplier},(r:any)=>{if(!r?.ok)return cb(r);saveSession({roomCode:r.room.code,playerId:r.playerId,playerToken:r.playerToken});setMyPlayerId(r.playerId);setRoom(r.room)});
 const joinRoom=()=>socket.emit("join-room",{name:name.trim(),code:roomCode.trim().toUpperCase()},(r:any)=>{if(!r?.ok)return cb(r);saveSession({roomCode:r.room.code,playerId:r.playerId,playerToken:r.playerToken});setMyPlayerId(r.playerId);setRoom(r.room)});
 const emit=(event:string,payload:any)=>socket.emit(event,payload,cb);
 const leaveRoom=()=>{if(!room)return;if(!confirm("ออกจากห้องใช่ไหม? คะแนนและประวัติจะยังถูกเก็บไว้"))return;socket.emit("leave-room",{code:room.code},(r:any)=>{if(r?.ok){clearSession();setRoom(null);setGame(null);setMyPlayerId("")}else cb(r)});};
 const endGame=()=>{if(room&&confirm("จบเกมสำหรับทุกคนใช่ไหม?"))emit("end-game",{code:room.code})};
 const sendEmoji=(emoji:string)=>{if(!room||emojiRemaining<=0)return;socket.emit("emoji-reaction",{code:room.code,emoji},(r:any)=>{if(r?.remaining!==undefined)setEmojiRemaining(r.remaining);if(!r?.ok&&r?.message!=="กดเร็วเกินไป")setError(r?.message||"")});};

 function CardView({card,selectable=false}:{card:Card;selectable?:boolean}){const red=card.suit==="♥"||card.suit==="♦";return <button className={`playing-card ${red?"red-card":""} ${selectable?"selectable":""} ${selectedCard===card.id?"selected-card":""}`} disabled={!selectable} onClick={()=>selectable&&setSelectedCard(card.id)}><div className="rank">{card.rank}</div><div className="suit">{card.suit}</div></button>}
 function EmojiLayer(){return <div className="emoji-layer">{reactions.map(r=><div key={r.id} className="emoji-pop-left" style={{"--emoji-left":`${18+Math.floor(r.seed*5)*38}px`,"--emoji-drift":`${20+r.seed*90}px`} as React.CSSProperties}><div className="emoji-big">{r.emoji}</div><div className="emoji-name">{r.name}</div></div>)}</div>}
 function EmojiBar(){return <div className="emoji-section"><div className="emoji-counter">Emoji {emojiRemaining}/10</div><div className="emoji-bar">{["😂","🤣","😭","😡","😎","👏","🔥","💀","❤️","🤡"].map(e=><button key={e} disabled={emojiRemaining<=0} onClick={()=>sendEmoji(e)}>{e}</button>)}</div></div>}
 function Status({p}:{p:Player|TablePlayer}){return <span className={`status ${p.status.toLowerCase()}`}>{p.status}</span>}
 function LedgerModal(){if(!room||!showLedger)return null;const mine=room.ledger[myPlayerId]||{};return <div className="modal-bg"><div className="modal"><button className="modal-close" onClick={()=>setShowLedger(false)}>✕</button><h2>💰 CHIP SUMMARY</h2><div className="my-total"><span>{myPlayer?.name}</span><strong>{myPlayer?.totalChip||0}</strong></div>{room.players.filter(p=>p.id!==myPlayerId).map(p=><div className="ledger-row" key={p.id}><span>{p.name} <Status p={p}/></span><b>{mine[p.id]||0}</b></div>)}</div></div>}

 if(restoring&&!room)return <div className="restore-page">กำลังกลับเข้าเกม...</div>;
 if(!room)return <div className="app"><header><div className="logo">🃏 31 SCAT</div><div>{connected?"Server Online":"Connecting"}</div></header><main className="home"><section className="hero"><h1>31 <span>SCAT</span></h1></section><section className="panel"><input value={name} onChange={e=>setName(e.target.value)} placeholder="ชื่อผู้เล่น"/><div className="multipliers">{[1,2,5,10].map(v=><button className={multiplier===v?"selected":""} onClick={()=>setMultiplier(v)} key={v}>{v}×</button>)}</div><button className="primary" onClick={createRoom}>CREATE ROOM</button><input value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())} placeholder="ROOM CODE" maxLength={4}/><button className="secondary" onClick={joinRoom}>JOIN ROOM</button>{error&&<div className="error">{error}</div>}</section></main></div>;
 if(room.status==="ended")return <div className="app"><header><div className="logo">🃏 31 SCAT</div></header><main className="final-page"><h1>GAME OVER</h1>{[...room.players].sort((a,b)=>b.totalChip-a.totalChip).map(p=><div className="final-player" key={p.id}><strong>{p.name}</strong><Status p={p}/><b>{p.totalChip} CHIP</b></div>)}</main></div>;
 if(room.status==="waiting"||!game)return <div className="app"><LedgerModal/><header><div><div className="logo">🃏 31 SCAT</div><div>ROOM {room.code}</div></div><div className="header-buttons"><button onClick={()=>setShowLedger(true)}>💰 CHIP</button><button onClick={leaveRoom}>🚪 LEAVE</button></div></header><main className="room-page"><div className="players">{room.players.map(p=><div className="player" key={p.id}><div className="avatar">{p.name[0]}</div><strong>{p.name}</strong><Status p={p}/><div>{p.totalChip} CHIP</div></div>)}</div>{isHost?<button className="start-button" onClick={()=>emit("start-game",{code:room.code})}>START GAME</button>:<div className="waiting">รอ Host</div>}</main></div>;
 if(game.phase==="showdown"&&game.result)return <div className="app"><EmojiLayer/><LedgerModal/><header><div><div className="logo">🃏 31 SCAT</div><div>ROUND {game.roundNumber}</div></div><div className="header-buttons"><button onClick={()=>setShowLedger(true)}>💰 CHIP</button><button onClick={leaveRoom}>🚪 LEAVE</button>{isHost&&<button className="end-button" onClick={endGame}>END GAME</button>}</div></header><main className="result-page"><h1>SHOWDOWN</h1><div className="result-grid">{room.players.map(p=><div className="result-player" key={p.id}><h3>{p.name}</h3><Status p={p}/><div className="big-score">{game.result!.scores[p.id]??"-"}</div><div>{game.result!.roundNet[p.id]??0} CHIP</div><small>TOTAL {p.totalChip}</small></div>)}</div><EmojiBar/>{isHost&&<button className="next-round" onClick={()=>emit("next-round",{code:room.code})}>NEXT ROUND</button>}</main></div>;
 return <div className="app"><EmojiLayer/><LedgerModal/><header><div><div className="logo">🃏 31 SCAT</div><div>ROOM {room.code} · ROUND {game.roundNumber}</div></div><div className="header-buttons"><button onClick={()=>setShowLedger(true)}>💰 CHIP</button><button onClick={leaveRoom}>🚪 LEAVE</button>{isHost&&<button className="end-button" onClick={endGame}>END GAME</button>}</div></header><main className="game-page"><section className="real-table"><div className="opponents">{game.tablePlayers.map(p=><div className={`opponent ${game.currentPlayerId===p.id?"current-player":""} ${p.status!=="ACTIVE"?"disconnected-player":""}`} key={p.id}><strong>{p.name}</strong><Status p={p}/><div className="card-backs">{Array.from({length:p.cardCount}).map((_,i)=><div className="card-back" key={i}>🂠</div>)}</div><small>{p.totalChip} CHIP</small></div>)}</div><div className="table-center"><button className="deck-stack" disabled={!myTurn||game.hasDrawn||!connected} onClick={()=>emit("draw-deck",{code:room.code})}>🂠<small>DECK</small></button><button className="discard-stack" disabled={!myTurn||game.hasDrawn||!game.topDiscard||!connected} onClick={()=>emit("draw-discard",{code:room.code})}>{game.topDiscard&&<CardView card={game.topDiscard}/>}<small>DISCARD</small></button></div><div className={`my-area ${myTurn?"my-turn":""}`}><div className="turn-label">{myTurn?"YOUR TURN":`TURN: ${playerName(game.currentPlayerId||"")}`}</div><div className="my-hand">{game.hand.map(c=><CardView key={c.id} card={c} selectable={myTurn&&game.hasDrawn&&connected}/>)}</div><div className="score-preview">SCORE: {score}</div><div className="actions">{myTurn&&!game.hasDrawn&&<><button className="action draw" onClick={()=>emit("draw-deck",{code:room.code})}>DRAW DECK</button><button className="action draw" onClick={()=>emit("draw-discard",{code:room.code})}>DRAW DISCARD</button>{game.phase==="playing"&&<button className="action knock" onClick={()=>emit("knock",{code:room.code})}>KNOCK</button>}</>}{myTurn&&game.hasDrawn&&<button className="action discard" disabled={!selectedCard} onClick={()=>socket.emit("discard-card",{code:room.code,cardId:selectedCard},cb)}>DISCARD SELECTED</button>}</div></div><EmojiBar/></section>{error&&<div className="error">{error}</div>}</main></div>;
}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
